// <auto-generated />
namespace CodeFirstUsingFluentApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class MappingLeftAndRightKeyForCourseTagTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MappingLeftAndRightKeyForCourseTagTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201911271817435_MappingLeftAndRightKeyForCourseTagTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
