// <auto-generated />
namespace CodeFirstExistingDatabase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview3-19553-01")]
    public sealed partial class IntialModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntialModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201911251401563_IntialModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
